version: '3.8'

services:
  mysql:
    image: mysql
    container_name: app-mysql
    volumes:
      - mysql_data:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=devops_db
    ports:
      - "3306:3306"
    networks:
      - app-networks
  backend:
    image: ${DOCKER_USER}/app-backend:${BUILD_TAG}
    container_name: backend
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=${DB_PASS}
      - DB_NAME=devops_db
    ports:
      - "5001:5001"
    depends_on:
      - mysql
    networks:
      - app-networks
  frontend:
    image: ${DOCKER_USER}/app-backend:${BUILD_TAG}
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge
volumes:
  mysql-data:


